/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkdayCalculatorRouteImport } from './routes/workday-calculator'
import { Route as AgeDifferenceRouteImport } from './routes/age-difference'
import { Route as IndexRouteImport } from './routes/index'

const WorkdayCalculatorRoute = WorkdayCalculatorRouteImport.update({
  id: '/workday-calculator',
  path: '/workday-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeDifferenceRoute = AgeDifferenceRouteImport.update({
  id: '/age-difference',
  path: '/age-difference',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/age-difference': typeof AgeDifferenceRoute
  '/workday-calculator': typeof WorkdayCalculatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/age-difference': typeof AgeDifferenceRoute
  '/workday-calculator': typeof WorkdayCalculatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/age-difference': typeof AgeDifferenceRoute
  '/workday-calculator': typeof WorkdayCalculatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/age-difference' | '/workday-calculator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/age-difference' | '/workday-calculator'
  id: '__root__' | '/' | '/age-difference' | '/workday-calculator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgeDifferenceRoute: typeof AgeDifferenceRoute
  WorkdayCalculatorRoute: typeof WorkdayCalculatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workday-calculator': {
      id: '/workday-calculator'
      path: '/workday-calculator'
      fullPath: '/workday-calculator'
      preLoaderRoute: typeof WorkdayCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age-difference': {
      id: '/age-difference'
      path: '/age-difference'
      fullPath: '/age-difference'
      preLoaderRoute: typeof AgeDifferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgeDifferenceRoute: AgeDifferenceRoute,
  WorkdayCalculatorRoute: WorkdayCalculatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
